import test_project_ci_cd


def test_init() -> None:
    assert test_project_ci_cd.__version__ == "0.1.0"
    assert test_project_ci_cd.session is None
    assert test_project_ci_cd.ERROR_NO_SESSIONS_FOUND == "No session found"
    assert test_project_ci_cd.login("admin", "admin1")
    assert test_project_ci_cd.is_session_active()
    test_project_ci_cd.print_username()
    test_project_ci_cd.logout()
    assert not test_project_ci_cd.is_session_active()
    test_project_ci_cd.print_username()
    assert test_project_ci_cd.login("admin", "admin1")
    assert test_project_ci_cd.is_session_active()
    test_project_ci_cd.logout()
    assert not test_project_ci_cd.is_session_active()
    assert not test_project_ci_cd.login("admin", "admin2")
    assert not test_project_ci_cd.is_session_active()
    test_project_ci_cd.print_username()
    assert test_project_ci_cd.login("admin", "admin1")
    assert test_project_ci_cd.is_session_active()
    test_project_ci_cd.logout()
    assert not test_project_ci_cd.is_session_active()
    assert test_project_ci_cd.login("admin", "admin1")
    assert test_project_ci_cd.is_session_active()
    test_project_ci_cd.logout()
    assert not test_project_ci_cd.is_session_active()
    assert test_project_ci_cd.login("admin", "admin1")
    assert test_project_ci_cd.is_session_active()
    test_project_ci_cd.logout()
    assert not test_project_ci_cd.is_session_active()
    assert test_project_ci_cd.login("admin", "admin1")
    assert test_project_ci_cd.is_session_active()
    test_project_ci_cd.logout()
    assert not test_project_ci_cd.is_session_active()
    assert test_project_ci_cd.login("admin", "admin1")
    assert test_project_ci_cd.is_session_active()
    test_project_ci_cd.logout()
    assert not test_project_ci_cd.is_session_active()
    assert test_project_ci_cd.login("admin", "admin1")
    assert test_project_ci_cd.is_session_active()
    test_project_ci_cd.logout()
    assert not test_project_ci_cd.is_session_active()
