---
name: default CI/CD pipeline
on:
  push:
    branches:
      - dev
      - main
      - issue/*
  pull_request:
    types: [opened, synchronize, reopened]  # Needed to make sure PRs are tested
    branches: 
      - dev
      - main

jobs:
   default:
     name: default workflow
     uses: DarylStark/development_toolchain/.github/workflows/workflow-python-library.yml@issue-2/ci-cd-pipelines
     with:
        python-versions: '["3.12"]'
        main-python-version: '3.12'
     secrets:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       PROJECT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}