---
name: Deploy project
on:
  push:
    tags: '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy project
        run: |
          echo "Deploying project"
          echo "Deployed project"