---
name: Linting and testing for development
on:
  push:
    branches-ignore:
      - main
      - container
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  default:
    name: default workflow
    uses: DarylStark/development_toolchain/.github/workflows/workflow-python-poetry.yml@issue-2/ci-cd-pipelines
    with:
       python-versions: '["3.10","3.11","3.12"]'
       main-python-version: '3.12'
       run-container-lint: true
       extra-poetry-groups: "dev"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}