---
name: Linting and testing for development
on:
  push:
    branches:
      - main

jobs:
   default:
     name: default workflow
     uses: DarylStark/development_toolchain/.github/workflows/workflow-python-poetry.yml@issue-2/ci-cd-pipelines
     with:
        python-versions: '["3.12"]'
        main-python-version: '3.12'
        publish-to-pypi: true
        new-version-tag: final
        run-container-lint: true
     secrets:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}