---
on:
  push:
    branches:
      - dev

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Debug
      run: |
        git log --oneline
        git branch -vva