---
name: Linting and testing for development
on:
  push:
    branches:
      - container

jobs:
  default:
    name: default workflow
    uses: DarylStark/development_toolchain/.github/workflows/publish-container.yml@issue-2/ci-cd-pipelines
    with:
       container-file: Containerfile
       container-tags: docker.io/dast1986/test-project-ci-cd:latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}